import Mathlib.Algebra.Group.Defs
import Mathlib.Data.Fin.Basic

namespace Zklib.Core

/--
An indexed multiplicative evaluation domain generated by a single element.

This keeps the first domain abstraction small and explicit: later polynomial,
NTT, and verifier layers can all talk about the same canonical `Fin size`
indexing before we commit to richer field-specific structure. It is
intentionally a cyclic, generator-indexed domain, not yet a general subgroup or
coset abstraction.
-/
structure EvaluationDomain (F : Type*) [Monoid F] where
  size : Nat
  size_pos : 0 < size
  generator : F
  generator_pow_size_eq_one : generator ^ size = 1
  generator_pow_injective : Function.Injective (fun i : Fin size => generator ^ (i : Nat))

/--
An explicit alias that makes the current scope visible at call sites.
-/
abbrev GeneratorIndexedEvaluationDomain := EvaluationDomain

/--
An explicit alias for the current cyclic domain abstraction.
-/
abbrev CyclicEvaluationDomain := EvaluationDomain

namespace EvaluationDomain

variable {F : Type*} [Monoid F]

/--
The canonical enumeration of domain points by powers of the generator.
-/
def point (domain : EvaluationDomain F) (i : Fin domain.size) : F :=
  domain.generator ^ (i : Nat)

end EvaluationDomain

/--
A coset-shaped evaluation domain obtained by shifting a cyclic base domain.

This records the next abstraction layer above `EvaluationDomain` without
changing the existing NTT-facing interface: a base cyclic domain still provides
the indexing and generator, while `shift` moves the points into a coset.
-/
structure CosetEvaluationDomain (F : Type*) [Monoid F] where
  base : EvaluationDomain F
  shift : F
  shift_point_injective : Function.Injective (fun i : Fin base.size => shift * base.point i)

namespace CosetEvaluationDomain

variable {F : Type*} [Monoid F]

/--
The canonical enumeration of coset points by shifting the base-domain points.
-/
def point (domain : CosetEvaluationDomain F) (i : Fin domain.base.size) : F :=
  domain.shift * domain.base.point i

/--
View a cyclic evaluation domain as the trivial coset shifted by `1`.
-/
def ofBase (base : EvaluationDomain F) : CosetEvaluationDomain F where
  base := base
  shift := 1
  shift_point_injective := by
    intro i j hij
    apply base.generator_pow_injective
    simpa [EvaluationDomain.point] using hij

end CosetEvaluationDomain

end Zklib.Core

