import Mathlib.Algebra.Group.Defs
import Mathlib.Data.Fin.Basic

namespace Zklib.Core

/--
An indexed multiplicative evaluation domain generated by a single element.

This keeps the first domain abstraction small and explicit: later polynomial,
NTT, and verifier layers can all talk about the same canonical `Fin size`
indexing before we commit to richer field-specific structure. It is
intentionally a cyclic, generator-indexed domain, not yet a general subgroup or
coset abstraction.
-/
structure EvaluationDomain (F : Type*) [Monoid F] where
  size : Nat
  size_pos : 0 < size
  generator : F
  generator_pow_size_eq_one : generator ^ size = 1
  generator_pow_injective : Function.Injective (fun i : Fin size => generator ^ (i : Nat))

/--
An explicit alias for the current cyclic domain abstraction.

`EvaluationDomain` remains as the short name during the early repository phase,
but this alias makes the intended scope visible at call sites and in docs.
-/
abbrev CyclicEvaluationDomain := EvaluationDomain

namespace EvaluationDomain

variable {F : Type*} [Monoid F]

/--
The canonical enumeration of domain points by powers of the generator.
-/
def point (domain : EvaluationDomain F) (i : Fin domain.size) : F :=
  domain.generator ^ (i : Nat)

end EvaluationDomain

end Zklib.Core
